### ISSUE TITLE
[PB1-01] Membuat Landing Page

### ISSUE THREAD

**Issue by nitasuarii** [SI-RPL-2022/SI4301_E_DnJ.id#1]
Personal user dan Organizational user dapat melihat dan mengakses halaman utama dari web DnJ.id.

![User-Sebelum Login](https://user-images.githubusercontent.com/92239727/164135111-b0e433a8-18be-42c2-993a-f37ca2ee7d53.png)
![User- Setelah Login-1](https://user-images.githubusercontent.com/92239727/164135116-38adf1d1-9598-470a-a4da-ab4da8fe092e.png)

**Comment by nitasuarii** [comment]
![User-Sebelum Login](https://user-images.githubusercontent.com/92239727/163954404-b2c520db-c0ab-4885-9c65-3c502cd9373e.png)

**Comment by tienfkusumasari** [comment]
sudah jalan logic nya (SP2)
