### ISSUE TITLE
[PB2-05] Membuat Pekerjaan

### ISSUE THREAD

**Issue by mrayhanabdillah** [SI-RPL-2022/SI4301_E_DnJ.id#12]
Admin dapat menambahkan, menghapus dan mengedit serta menampilkan pelatihan yang akan ditampilkan pada website DnJ.id

1. Admin sudah berada pada halaman admin
2. Admin mengklik pekerjaan kemudian mengklik button "Tambah Pekerjaan"
3. Admin mengisi data-data pekerjaan yang akan ditampilkan pada website DnJ.id
4. Admin menyimpan data-data pekerjaan dan card pekerjaan terbuat pada halaman website DnJ.id

![Admin - Pekerjaan](https://user-images.githubusercontent.com/92239727/168128371-ebf29089-55cb-4003-8836-c2076f62db08.png)
![Tambah Pekerjaan](https://user-images.githubusercontent.com/92239727/168128393-26aae6f8-97ef-4b62-ae14-8794398ae683.png)
![Edit Pekerjaan](https://user-images.githubusercontent.com/92239727/168128407-ebadab0e-cf2f-4ca6-a3d0-561567b9c7ee.png)

**Comment by tienfkusumasari** [comment]
done
