### ISSUE TITLE
[PB2-04] Membuat Pelatihan

### ISSUE THREAD

**Issue by mrayhanabdillah** [SI-RPL-2022/SI4301_E_DnJ.id#13]
Admin dapat menambahkan, menghapus dan mengedit serta menampilkan pelatihan yang akan ditampilkan pada website DnJ.id

1. Admin sudah berada pada halaman admin
2. Admin mengklik pekerjaan kemudian mengklik button "Tambah Pelatihan"
3. Admin mengisi data-data pelatihan yang akan ditampilkan pada website DnJ.id
4. Admin menyimpan data-data pelatihan dan card pelatihan terbuat pada halaman website DnJ.id

![Admin - Pelatihan 2](https://user-images.githubusercontent.com/65312084/171264021-d07e48b6-e7b2-4b38-a459-2fea2ad9ee56.png)
![Penambahan Pelatihan - Admin ( Online )](https://user-images.githubusercontent.com/65312084/171269124-1a86448b-01c4-4b52-8a15-229a48f7f933.png)
![Penambahan Pelatihan - Admin ( Onsite)](https://user-images.githubusercontent.com/65312084/171269184-483fb33f-507a-4fb2-9234-2b905c63fb63.png)

**Comment by tienfkusumasari** [comment]
done, salah menentukan tipe data di bagian kontak person . tambahkan konstrain tipe data di isseu

**Comment by tienfkusumasari** [comment]
done
