### ISSUE TITLE
[PB2-03] Membuat Profil Pengguna

### ISSUE THREAD

**Issue by mrayhanabdillah** [SI-RPL-2022/SI4301_E_DnJ.id#14]
Sebagai Personal User dan Organizational User bisa menampilkan halaman profil yang berisi riwayat aktivitas pelatihan, pekerjaan serta mengedit profil. 

1. User berada pada halaman utama website
2. User mengklik icon person pada kanan atas
3. User memilih "profile" pada icon person di pojok kanan atas
4. User masuk ke halaman profil dan bisa melihat biodata dan riwayat aktivitas yang dilakukan pada website DnJ
5. Jika ada biodata yang salah, user dapat mengklik icon edit pada biodata
6. Selanjutnya user menginputkan data yang benar dan menyimpan perubahan yang telah dibuat
![Halaman-Profile](https://user-images.githubusercontent.com/92239727/164478142-db8f5186-aa9f-4364-b4a9-e3022120f605.png)

**Comment by tienfkusumasari** [comment]
benerin logic passwd

**Comment by tienfkusumasari** [comment]
close di sprint 3 (update passwd dan profil)
