### ISSUE TITLE
[PB2-02] Mencari Pelatihan

### ISSUE THREAD

**Issue by mrayhanabdillah** [SI-RPL-2022/SI4301_E_DnJ.id#15]
Sebagai personal user dapat mencari pelatihan yang tersedia pada halaman pelatihan, melihat detail dari pelatihan yang dipilih dan mengakses langsung ke halaman penyedia pelatihan (link eksternal)

1. Personal user mengakses halaman utama
2. Personal user mencari pelatihan yang diminati
3. Personal user mengklik pelatihan yang diminati untuk melihat detail pelatihan
4. Jika tertarik, personal user mengklik button "Daftar Sekarang"
5. Selanjutnya halaman website akan mengarahkan ke halaman penyedia pelatihan (link eksternal)

![Halaman-Pelatihan](https://user-images.githubusercontent.com/92239727/164476813-05b64707-618c-4162-b890-96b33ce7b351.png)
![Daftar Pelatihan](https://user-images.githubusercontent.com/92239727/164476830-b2d945e3-8e28-43ea-b588-321f172dd3b8.png)

**Comment by tienfkusumasari** [comment]
button daftar sekarang ==> belum di konek ke link eksternal (di input nya belm ada masukan link eksternal)==> taro di sprint 3
