### ISSUE TITLE
[PB2-01] Mencari Pekerjaan

### ISSUE THREAD

**Issue by mrayhanabdillah** [SI-RPL-2022/SI4301_E_DnJ.id#16]
Sebagai personal user dapat mencari pekerjaan yang tersedia pada halaman pekerjaan, melihat detail dari pekerjaan yang dipilih dan mengakses langsung ke halaman penyedia kerja (link eksternal)

1. Personal user mengakses halaman utama
2. Personal user mencari pekerjaan yang diminati
3. Personal user mengklik pekerjaan yang diminati untuk melihat detail pekerjaan
4. Jika tertarik, personal user mengklik button "Daftar Sekarang" 
5. Selanjutnya halaman website akan mengarahkan ke halaman penyedia pekerjaan (link eksternal)

![Halaman-Pekerjaan](https://user-images.githubusercontent.com/92239727/164475870-9feefd2c-5e43-481b-9bdf-3abccd93bfbb.png)
![Detail Pekerjaan](https://user-images.githubusercontent.com/92239727/164475990-162061f8-0401-4008-8e37-2443aa3e4432.png)

**Comment by tienfkusumasari** [comment]
done , button apply sekarang belum jalan ke link eksternal (SP3) saran = tambahkan field di form input pekerjaan dengan llink eksternal (url)
