### ISSUE TITLE
[PB1-05B] Melihat Riwayat Donasi Organizational User

### ISSUE THREAD

**Issue by nitasuarii** [SI-RPL-2022/SI4301_E_DnJ.id#17]
Organizational User dapat melihat riwayat donasi yang pernah dibuat dan dilakukan dalam website DnJ.id

1. User berada pada halaman donasi
2. User mengklik icon history
3. Halaman history muncul dan menampilkan berbagai aktivitas donasi yang pernah dilakukan (donasi yang dilakukan  atau donasi yang dibuat)

![Hitory Donasi - organizational user](https://user-images.githubusercontent.com/92239727/173387340-0dd4c6fc-a07f-4d00-9c80-353bfeba2692.png)

**Comment by tienfkusumasari** [comment]
close (SP3)
