### ISSUE TITLE
[PB1-03] Melakukan Registrasi

### ISSUE THREAD

**Issue by nitasuarii** [SI-RPL-2022/SI4301_E_DnJ.id#3]
Personal User dan Organizational User dapat melakukan registrasi pada web DnJ.id. 

![Register](https://user-images.githubusercontent.com/92239727/164134853-2016f9f5-592f-4f80-92eb-8f6063770e6a.png)

**Comment by nitasuarii** [comment]
![Register](https://user-images.githubusercontent.com/92239727/163954163-e9e4a55e-2701-4a06-8f78-35e625407751.png)

**Comment by tienfkusumasari** [comment]
DONE
