### ISSUE TITLE
[PB1-04] Melakukan Donasi

### ISSUE THREAD

**Issue by nitasuarii** [SI-RPL-2022/SI4301_E_DnJ.id#4]
Personal User dapat melihat donasi yang tersedia dan melakukan donasi hingga selesai. 

1. Personal user berada di halaman utama website dan mengklik menu donasi pada navbar
2. Halaman website menampilakn daftar donasi yang sedang digalangkan
3. Personal user memilih donasi yang ingin dilakukan
4. Personal user mengisikan data diri dan nominal donasi
5. Selanjutnya personal user memilih metode pembayaran
6. Kemudian personal user melakukan pembayaran sesuai dengan batas waktu yang telah ditentukan
7. Selanjutnya personal user mengupload bukti pembayaran
8. Sistem menampilkan bahwa donasi berhasil dilakukan

![Halaman-Donasi](https://user-images.githubusercontent.com/92239727/164134363-5132c689-fa18-4126-b372-10e7ff3db086.png)
![Form Donasi - Personal user](https://user-images.githubusercontent.com/92239727/164134387-a65b8c91-5d41-405c-8236-44c65a965f9f.png)
![Pembayaran Pending](https://user-images.githubusercontent.com/92239727/164134533-d9f8f57e-5631-406f-801e-cf712214c7d1.png)
![Bukti Pembayaran - Personal User](https://user-images.githubusercontent.com/92239727/164134617-69e40627-2fc3-450d-9c2f-a804b580c537.png)
![Bukti Pembayaran - Personal User-1](https://user-images.githubusercontent.com/92239727/164134657-606e0987-f040-4a91-89f6-34447c7891ac.png)

**Comment by nitasuarii** [comment]
![Detail donasi- personal user](https://user-images.githubusercontent.com/92239727/163953994-8ba6204e-278f-4a8c-ad96-235e0114591e.png)
![Halaman-Donasi](https://user-images.githubusercontent.com/92239727/163954003-cfba962c-2ba8-4849-a1c4-32298c82d340.png)
![Pembayaran Pending](https://user-images.githubusercontent.com/92239727/163954006-5b6517cb-758d-4e29-93e3-c5531b7f288a.png)

**Comment by nitasuarii** [comment]
![Form Donasi - Personal user-1](https://user-images.githubusercontent.com/92239727/163955186-857eb710-4457-400a-832a-b771750b8f6a.png)
![Notif-berhasil buat donasi](https://user-images.githubusercontent.com/92239727/163955247-d02fb401-cf68-4335-9457-11fed9396713.png)

**Comment by nitasuarii** [comment]
![Form Donasi - Personal user](https://user-images.githubusercontent.com/92239727/163955443-744695db-326d-4cfb-87c9-5d905b9ef080.png)

**Comment by nitasuarii** [comment]
![Buat Donasi](https://user-images.githubusercontent.com/92239727/163970797-31aad641-d9bf-4eda-abff-12ad592132b4.png)
![Bukti Pembayaran - Personal User](https://user-images.githubusercontent.com/92239727/163970811-080a8173-e55b-486e-abf5-a7e84fcaad5b.png)
![Form Donasi - Personal user](https://user-images.githubusercontent.com/92239727/163970815-a705d796-1463-495e-9c1d-2b284c652389.png)
![Halaman-Donasi](https://user-images.githubusercontent.com/92239727/163970821-b291292c-6c51-4ffd-8094-2768f45d00dc.png)

**Comment by nitasuarii** [comment]
![Pembayaran Pending](https://user-images.githubusercontent.com/92239727/163970934-d6c279c1-dbac-4c93-b130-9c98db4b93ea.png)

**Comment by tienfkusumasari** [comment]
logic donasi udah dibuat (SP2) untuk logic upload nya belum selesai
