### ISSUE TITLE
[PB1-06] Membuat Donasi

### ISSUE THREAD

**Issue by mrayhanabdillah** [SI-RPL-2022/SI4301_E_DnJ.id#7]
![Buat Donasi](https://user-images.githubusercontent.com/92259034/164152449-8267622b-d578-4b5a-9aa3-70942c4be436.png)
Sebagai Organizational User dapat membuat donasi untuk tempat melakukan program donasi.

Organizational User melakukan klik pada buat donasi lalu mengisi form dan klik buat donasi
![Halaman-Donasi](https://user-images.githubusercontent.com/92259034/164152439-922018c0-650e-4cb4-82d2-e51d27a07124.png)

**Comment by tienfkusumasari** [comment]
done (SP2)
