### ISSUE TITLE
[PB3-03] Menerima Donasi

### ISSUE THREAD

**Issue by mrayhanabdillah** [SI-RPL-2022/SI4301_E_DnJ.id#8]
User Personal dapat menerima hasil donasi yang sudah dibuat. 

1. User Organizational Melihat Riwayat Donasi
2.  User  Organizational melihat detail dari donasi yang telah dibuat
3. Kemudian, user organizational menambahkan ID dan keterangan user penerima donasi
4. Selanjutnya, Admin melihat halaman donasi
5. dan melakukan verifikasi penerimaan donasi 

![Halaman Penerimaan Donasi - Organizational user](https://user-images.githubusercontent.com/92239727/175827390-50468383-153d-42ec-bd88-9cbdef5b282c.png)

![Halaman Pengiriman Donasi - Organizational user](https://user-images.githubusercontent.com/92239727/175827471-3a30de71-2e14-493f-92bd-b51faf9520a0.png)

![Halaman Pengiriman Donasi - Organizational user-1](https://user-images.githubusercontent.com/92239727/175827536-5c2b4744-7984-42e8-b48c-7d8a8ac7fb20.png)

![Halaman Transaksi Pending - Organizational user](https://user-images.githubusercontent.com/92239727/175827543-c3792c9b-6051-45f9-a960-95227d50418b.png)

![Verifikasi Transaksi Donasi - Admin-1](https://user-images.githubusercontent.com/92239727/175827552-de6853bd-c0f1-4d57-973d-29d6160c423a.png)
![Verifikasi Transaksi Donasi - Admin](https://user-images.githubusercontent.com/92239727/175827558-ec78e6fd-5f1c-4245-b4b9-d636d898e920.png)

**Comment by tienfkusumasari** [comment]
close (SP3)
