### ISSUE TITLE
[PB3-02] Melihat Riwayat Donasi

### ISSUE THREAD

**Issue by mrayhanabdillah** [SI-RPL-2022/SI4301_E_DnJ.id#9]
Admin dapat melihat seluruh riwayat donasi yang telah dibuat sebelumnya. 

1. Admin mengakses halaman admin
2. Admin masuk ke halaman donasi > riwayat donasi
3. Halaman riwayat donasi menampilkan seluruh donasi yang pernah dibuat
![Admin-Dashboard](https://user-images.githubusercontent.com/92239727/173388365-f1b000a2-a961-4dc6-a554-eec344080254.png)

**Comment by tienfkusumasari** [comment]
close
